spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monolithdb
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/monolith-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8080
  servlet:
    context-path: /api

keycloak:
  realm: monolith-realm
  auth-server-url: http://localhost:8180
  ssl-required: external
  resource: monolith-client
  credentials:
    secret: your-client-secret
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE